[package]
name = "rbx-bytesoft/platform-game"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1.7.0"
TableUtil = "sleitnick/table-util@1.2.1"
Trove = "sleitnick/trove@1.1.0"
Signal = "sleitnick/signal@2.0.1"
Promise = "evaera/promise@4.0.0"
Component = "sleitnick/component@2.4.6"
Vide = "centau/vide@0.2.0"

[server-dependencies]
ProfileService = "nidoxs/profileservice@1.0.0"